# Generated by Django 6.0.3 on 2026-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('INCREMENT', 'Increment'), ('DECREMENT', 'Decrement'), ('RESET', 'Reset')], help_text='Type of counter action', max_length=10)),
                ('value', models.IntegerField(help_text='Counter value after this action')),
                ('comment', models.TextField(blank=True, help_text='Optional comment about this action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this action occurred')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='counter_cou_timesta_9ea587_idx'), models.Index(fields=['action'], name='counter_cou_action_f02d6f_idx')],
            },
        ),
    ]
