# Generated by Django 6.0.1 on 2026-01-21 10:08

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_mixer_pipeline_mixer'), ('api', '0003_preferencesaudiobackend'), ('api', '0004_remove_preferencesaudiobackend_plugin'), ('api', '0005_audiopipeline'), ('api', '0006_audiopipelinenode_audiopipelineedge'), ('api', '0007_pulseaudiotunnelnode'), ('api', '0008_audiopipelineionode_and_more'), ('api', '0009_remove_pulseaudiotunnelnode_audiopipelineionode_ptr_and_more'), ('api', '0010_remove_audiopipelinenode_kind_and_more'), ('api', '0011_remove_audiopipelinenode_parameters'), ('api', '0012_audiopipelinedevicenode'), ('api', '0013_rename_pipeline_camilladsppipeline'), ('api', '0014_camilladspaudiopipelinenode'), ('api', '0015_audiopipelinenode_type_name'), ('api', '0016_alter_audiopipelinenode_type_name'), ('api', '0017_alter_audiopipelinenode_type_name_and_more'), ('api', '0018_alter_audiopipelinenodeslot_id_and_more'), ('api', '0019_rename_node_a_audiopipelineedge_slot_a_and_more'), ('api', '0020_remove_audiopipelinenodeslot_pk_and_more'), ('api', '0021_alter_pulseaudiotunnelnode_mode'), ('api', '0022_alter_pulseaudiotunnelnode_server'), ('api', '0023_audiopipelineapplyevent_audiopipelineapplyjob'), ('api', '0024_remove_audiopipelineapplyevent_job_id_and_more'), ('api', '0025_remove_audiopipelineapplyjob_api_audiopipelineapplyjob_status_jobstatus_and_more'), ('api', '0026_remove_audiopipelineapplyevent_api_audiopipelineapplyevent_event_type_eventtype_and_more'), ('api', '0027_pulseaudiocreatedmodule_pulseaudiotunnelnodestate'), ('api', '0028_audiopipeline_stale'), ('api', '0029_remove_audiopipelinenodeslot_api_audiopipelinenodeslot_type_slottype_and_more'), ('api', '0030_alter_pulseaudiotunnelnodestate_node'), ('api', '0031_pulseaudiopipenode_pulseaudiopipenodestate'), ('api', '0032_pulseaudiotunnelnodestate_device'), ('api', '0033_audiopipelinenodeposition')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=255)),
                ('sampling_rate', models.IntegerField()),
                ('format', models.CharField(choices=[('S16LE', '16-bit Signed Little Endian'), ('S24LE', '24-bit Signed Little Endian'), ('S32LE', '32-bit Signed Little Endian'), ('S16BE', '16-bit Signed Big Endian'), ('S24BE', '24-bit Signed Big Endian'), ('S32BE', '32-bit Signed Big Endian'), ('FLOAT32LE', '32-bit Floating Point Little Endian'), ('FLOAT32BE', '64-bit Floating Point Little Endian')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='KnownAudioDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(help_text="Audio backend name (e.g., 'pulseaudio')", max_length=50)),
                ('name', models.CharField(help_text='Device identifier', max_length=255)),
                ('device_type', models.CharField(choices=[('CAPTURE', 'Capture'), ('PLAYBACK', 'Playback')], max_length=10)),
                ('format', models.CharField(choices=[('S16LE', '16-bit Signed Little Endian'), ('S24LE', '24-bit Signed Little Endian'), ('S32LE', '32-bit Signed Little Endian'), ('S16BE', '16-bit Signed Big Endian'), ('S24BE', '24-bit Signed Big Endian'), ('S32BE', '32-bit Signed Big Endian'), ('FLOAT32LE', '32-bit Floating Point Little Endian'), ('FLOAT32BE', '32-bit Floating Point Big Endian'), ('U8', '8-bit Unsigned'), ('ALAW', 'A-law'), ('ULAW', 'μ-law'), ('S24_32LE', '24-bit in 32-bit Little Endian'), ('S24_32BE', '24-bit in 32-bit Big Endian')], max_length=15)),
                ('sample_rate', models.IntegerField(help_text='Sample rate in Hz')),
                ('channels', models.IntegerField(help_text='Number of audio channels')),
                ('active', models.BooleanField(default=False, help_text='Whether device is currently connected')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last time device was detected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['active'], name='api_knownau_active_306d30_idx'), models.Index(fields=['device_type'], name='api_knownau_device__c11311_idx')],
                'unique_together': {('backend', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly pipeline name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this pipeline')),
                ('samplerate', models.IntegerField(help_text='Processing sample rate in Hz (e.g., 44100, 48000, 96000)')),
                ('chunksize', models.IntegerField(default=1024, help_text='Number of samples per chunk (recommended: 1024 for 44.1/48kHz, 2048 for 88.2/96kHz, 4096 for 176.4/192kHz)')),
                ('enabled', models.BooleanField(default=False, help_text='Whether this pipeline is enabled')),
                ('active', models.BooleanField(default=False, help_text='Whether this pipeline is currently active/running')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_device', models.ForeignKey(help_text='Audio input (capture) device', limit_choices_to={'device_type': 'CAPTURE'}, on_delete=django.db.models.deletion.PROTECT, related_name='input_pipelines', to='api.knownaudiodevice')),
                ('output_device', models.ForeignKey(help_text='Audio output (playback) device', limit_choices_to={'device_type': 'PLAYBACK'}, on_delete=django.db.models.deletion.PROTECT, related_name='output_pipelines', to='api.knownaudiodevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('GAIN', 'Gain'), ('VOLUME', 'Volume'), ('LOUDNESS', 'Loudness'), ('DELAY', 'Delay'), ('FIR', 'FIR Filter'), ('IIR', 'IIR Filter'), ('BIQUAD', 'Biquad'), ('COMPRESSOR', 'Compressor'), ('LIMITER', 'Limiter'), ('EQ', 'Equalizer')], help_text='Type of filter', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Position in the filter chain (lower = earlier)')),
                ('config', models.JSONField(default=dict, help_text='Filter configuration parameters (JSON)')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this filter is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(help_text='Pipeline this filter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='api.pipeline')),
            ],
            options={
                'ordering': ['pipeline', 'order'],
                'indexes': [models.Index(fields=['pipeline', 'order'], name='api_filter_pipelin_0baa3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mixer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Mixer name (e.g., 'stereo_to_6ch')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this mixer')),
                ('input_channels', models.IntegerField(help_text='Number of input channels')),
                ('output_channels', models.IntegerField(help_text='Number of output channels')),
                ('mapping', models.JSONField(help_text='Channel mapping configuration (list of destination mappings)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pipeline',
            name='mixer',
            field=models.ForeignKey(blank=True, help_text='Optional mixer for channel mapping (auto-created if input/output channels differ)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='api.mixer'),
        ),
        migrations.CreateModel(
            name='PreferencesAudioBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the backend', max_length=255)),
                ('enabled', models.BooleanField(help_text='Whether this backend is enabled or not and should be used in device discovery')),
            ],
        ),
        migrations.CreateModel(
            name='AudioPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pipeline name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this pipeline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AudioPipelineNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.audiopipeline')),
                ('type_name', models.CharField(default=None, help_text="The type of the node, e.g. 'AudioProcessor'", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AudioPipelineDeviceNode',
            fields=[
                ('audiopipelinenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.audiopipelinenode')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.knownaudiodevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.audiopipelinenode',),
        ),
        migrations.RenameModel(
            old_name='Pipeline',
            new_name='CamillaDSPPipeline',
        ),
        migrations.CreateModel(
            name='CamillaDSPAudioPipelineNode',
            fields=[
                ('audiopipelinenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.audiopipelinenode')),
                ('camilladsp_pipeline', models.ForeignKey(help_text='The Camilla DSP pipeline associated with this node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_pipeline_nodes', to='api.camilladsppipeline', verbose_name='Camilla DSP Pipeline')),
            ],
            bases=('api.audiopipelinenode',),
        ),
        migrations.CreateModel(
            name='AudioPipelineNodeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name to identify this slot on it's node", max_length=255)),
                ('type', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'AUDIO'), (2, 'CONTROL')])),
                ('direction', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'INPUT'), (2, 'OUTPUT'), (3, 'ALL')])),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.audiopipelinenode')),
                ('nice_name', models.CharField(help_text='A nice name for this slot', max_length=255, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', [1, 2])), name='api_AudioPipelineNodeSlot_type_SlotType'), models.CheckConstraint(condition=models.Q(('direction__in', [1, 2, 3])), name='api_AudioPipelineNodeSlot_direction_SlotDirection')],
            },
        ),
        migrations.CreateModel(
            name='AudioPipelineEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='api.audiopipelinenodeslot')),
                ('slot_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='api.audiopipelinenodeslot')),
            ],
        ),
        migrations.CreateModel(
            name='PulseAudioTunnelNode',
            fields=[
                ('server', models.CharField(help_text='The server to connect to', max_length=255, null=True)),
                ('mode', models.CharField(choices=[('SOURCE', 'source'), ('SINK', 'sink')], help_text='The mode of the tunnel. Either source or sink', max_length=255, null=True)),
                ('source', models.CharField(help_text='The source on the remote server. Only available in source mode', max_length=255, null=True)),
                ('sink', models.CharField(help_text='The sink on the remote server. Only available in sink mode', max_length=255, null=True)),
                ('cookie', models.CharField(help_text='The authentication cookie file to use', max_length=255, null=True)),
                ('audiopipelinenode_ptr', models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.audiopipelinenode')),
            ],
            bases=('api.audiopipelinenode',),
        ),
        migrations.CreateModel(
            name='AudioPipelineApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enum.fields.EnumCharField(choices=[('STARTED', 'Started'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='STARTED', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.audiopipeline')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['STARTED', 'RUNNING', 'SUCCESS', 'FAILURE'])), name='api_AudioPipelineApplyJob_status_JobStatus')],
            },
        ),
        migrations.CreateModel(
            name='AudioPipelineApplyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', django_enum.fields.EnumCharField(choices=[('START', 'Start'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('COMPLETED_NODE', 'Completed Node')], max_length=14)),
                ('data', models.JSONField(null=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.audiopipelinenode')),
                ('job', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.audiopipelineapplyjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['START', 'SUCCESS', 'FAILURE', 'COMPLETED_NODE'])), name='api_AudioPipelineApplyEvent_event_type_EventType')],
            },
        ),
        migrations.RemoveConstraint(
            model_name='audiopipelineapplyjob',
            name='api_AudioPipelineApplyJob_status_JobStatus',
        ),
        migrations.AlterField(
            model_name='audiopipelineapplyjob',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('STARTED', 'Started'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='STARTED', max_length=7),
        ),
        migrations.AddConstraint(
            model_name='audiopipelineapplyjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['STARTED', 'RUNNING', 'SUCCESS', 'FAILED'])), name='api_AudioPipelineApplyJob_status_JobStatus'),
        ),
        migrations.RemoveConstraint(
            model_name='audiopipelineapplyevent',
            name='api_AudioPipelineApplyEvent_event_type_EventType',
        ),
        migrations.AlterField(
            model_name='audiopipelineapplyevent',
            name='event_type',
            field=django_enum.fields.EnumCharField(choices=[('START', 'Start'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('STARTED_NODE', 'Started Node'), ('COMPLETED_NODE', 'Completed Node')], max_length=14),
        ),
        migrations.AddConstraint(
            model_name='audiopipelineapplyevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['START', 'SUCCESS', 'FAILURE', 'STARTED_NODE', 'COMPLETED_NODE'])), name='api_AudioPipelineApplyEvent_event_type_EventType'),
        ),
        migrations.CreateModel(
            name='PulseAudioCreatedModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PulseAudioTunnelNodeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pulseaudiocreatedmodule')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='api.pulseaudiotunnelnode')),
            ],
        ),
        migrations.AddField(
            model_name='audiopipeline',
            name='stale',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveConstraint(
            model_name='audiopipelinenodeslot',
            name='api_AudioPipelineNodeSlot_type_SlotType',
        ),
        migrations.AlterField(
            model_name='audiopipelinenodeslot',
            name='type',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'DEVICE_AUDIO_OUTPUT'), (2, 'DEVICE_AUDIO_INPUT'), (3, 'AUDIO_CONSUMER'), (4, 'AUDIO_PRODUCER')]),
        ),
        migrations.AddConstraint(
            model_name='audiopipelinenodeslot',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', [1, 2, 3, 4])), name='api_AudioPipelineNodeSlot_type_SlotType'),
        ),
        migrations.AlterField(
            model_name='pulseaudiotunnelnodestate',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pulseaudiotunnelnode'),
        ),
        migrations.CreateModel(
            name='PulseAudioPipeNode',
            fields=[
                ('audiopipelinenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.audiopipelinenode')),
            ],
            bases=('api.audiopipelinenode',),
        ),
        migrations.CreateModel(
            name='PulseAudioPipeNodeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pulseaudiocreatedmodule')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pulseaudiopipenode')),
            ],
        ),
        migrations.AddField(
            model_name='pulseaudiotunnelnodestate',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.knownaudiodevice'),
        ),
        migrations.CreateModel(
            name='AudioPipelineNodePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='api.audiopipelinenode')),
            ],
        ),
    ]
