# Generated by Django 6.0.3 on 2026-04-08 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0037_pulseaudiopipenode_latency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulseaudiotunnelnodestate',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.knownaudiodevice'),
        ),
    ]
