# Generated by Django 6.0.3 on 2026-08-22 16:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_plan_state_and_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticRecord",
            fields=[
                ("sequence", models.BigAutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("correlation_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("category", models.CharField(max_length=128)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="debug",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("sequence",),
                "indexes": [
                    models.Index(
                        fields=["category", "captured_at"], name="api_diag_category_time_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RuntimeProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("projection_type", models.CharField(max_length=64)),
                ("subject_key", models.CharField(max_length=256)),
                ("world_generation", models.PositiveBigIntegerField()),
                ("world_sequence", models.PositiveBigIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("is_current", models.BooleanField(default=True)),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("projection_type", "subject_key", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["is_current", "created_at"],
                        name="api_runtime_current_time_idx",
                    ),
                    models.Index(
                        fields=["projection_type", "created_at"],
                        name="api_runtime_type_time_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("projection_type", "subject_key"),
                        name="api_runtime_projection_current_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("world_generation__gte", 1)),
                        name="api_runtime_projection_generation_positive",
                    ),
                ],
            },
        ),
    ]
