# Generated by Django 6.0.3 on 2026-08-22 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_runtime_records"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appliedplanstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_plan__isnull", True),
                    ("previous_plan__isnull", True),
                    models.Q(("current_plan", models.F("previous_plan")), _negated=True),
                    _connector="OR",
                ),
                name="api_applied_plan_distinct_rollback",
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("category", ""), _negated=True),
                name="api_diagnostic_category_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="api_graph_definition_name_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_digest", ""), _negated=True),
                name="api_graph_revision_digest_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="logicalendpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="api_logical_endpoint_name_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="manualoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_id", ""), _negated=True),
                name="api_manual_override_scope_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="manualoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="api_manual_override_reason_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="orchestrationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("event_type", ""), _negated=True),
                name="api_orchestration_event_type_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="resolvedplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("plan_digest", ""), _negated=True),
                name="api_resolved_plan_digest_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimeprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(("projection_type", ""), _negated=True),
                name="api_runtime_projection_type_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimeprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(("subject_key", ""), _negated=True),
                name="api_runtime_projection_subject_nonempty",
            ),
        ),
    ]
