# Generated by Django 6.0.3 on 2026-08-22 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_orchestration_resource_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="graphrevision",
            name="update_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="graphrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("update_version__gte", 1)),
                name="api_graph_revision_update_version_positive",
            ),
        ),
    ]
