# Generated by Django 6.0.3 on 2026-08-22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_graph_revision_update_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="resolvedplan",
            name="resolution_mode",
            field=models.CharField(
                choices=[("live", "Live candidate"), ("shadow", "Shadow only")],
                default="live",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ShadowResolutionComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("equivalent", models.BooleanField(default=False)),
                ("differences", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "baseline_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shadow_baseline_comparisons",
                        to="api.resolvedplan",
                    ),
                ),
                (
                    "shadow_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_comparison",
                        to="api.resolvedplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["equivalent", "created_at"],
                        name="api_shadow_compare_result_idx",
                    )
                ],
            },
        ),
    ]
