# Generated by Django 6.0.3 on 2026-08-22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_shadow_resolution_comparison"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CamillaDSPProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("version", models.PositiveIntegerField()),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("content", models.JSONField()),
                ("content_digest", models.CharField(editable=False, max_length=64)),
                ("validation_summary", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="camilladsp_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("profile_id", "version"),
                "indexes": [
                    models.Index(
                        fields=["owner", "name"],
                        name="api_camilladsp_owner_name_idx",
                    ),
                    models.Index(
                        fields=["content_digest"],
                        name="api_camilladsp_digest_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile_id", "version"),
                        name="api_camilladsp_profile_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="api_camilladsp_profile_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version", 1)),
                        name="api_camilladsp_profile_schema_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="api_camilladsp_profile_name_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("content_digest", ""), _negated=True),
                        name="api_camilladsp_profile_digest_nonempty",
                    ),
                ],
            },
        ),
    ]
