# Generated by Django 6.0.3 on 2026-08-23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_remove_legacy_audio_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedAudioAdapter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=64)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("configuration", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=False)),
                ("restart_generation", models.PositiveBigIntegerField(default=0)),
                ("update_version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="managed_audio_adapters", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("name", "id"),
                "indexes": [
                    models.Index(fields=["owner", "kind"], name="api_adapter_owner_kind_idx"),
                    models.Index(fields=["enabled"], name="api_adapter_enabled_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("owner", "name"), name="api_adapter_owner_name_unique"),
                    models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="api_adapter_name_nonempty"),
                    models.CheckConstraint(condition=models.Q(("kind", ""), _negated=True), name="api_adapter_kind_nonempty"),
                    models.CheckConstraint(condition=models.Q(("schema_version", 1)), name="api_adapter_schema_supported"),
                    models.CheckConstraint(condition=models.Q(("update_version__gte", 1)), name="api_adapter_version_positive"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ManagedAudioAdapterRuntimeState",
            fields=[
                ("adapter", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="runtime_state", serialize=False, to="api.managedaudioadapter")),
                ("lifecycle", models.CharField(choices=[("stopped", "Stopped"), ("starting", "Starting"), ("ready", "Ready"), ("stopping", "Stopping"), ("backoff", "Backoff"), ("error", "Error")], default="stopped", max_length=16)),
                ("health", models.CharField(choices=[("unknown", "Unknown"), ("healthy", "Healthy"), ("unhealthy", "Unhealthy")], default="unknown", max_length=16)),
                ("process_id", models.PositiveIntegerField(blank=True, null=True)),
                ("runtime_generation", models.PositiveBigIntegerField(default=0)),
                ("configuration_digest", models.CharField(blank=True, max_length=64)),
                ("expected_node_name", models.CharField(blank=True, max_length=255)),
                ("runtime_key", models.CharField(blank=True, max_length=256, null=True)),
                ("progress", models.JSONField(blank=True, default=dict)),
                ("retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("adapter_id",),
                "indexes": [models.Index(fields=["lifecycle", "retry_at"], name="api_adapter_lifecycle_idx")],
            },
        ),
    ]
