# Generated by Django 6.0.3 on 2026-08-29 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_audio_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginCapabilityState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_id', models.CharField(max_length=128)),
                ('capability_id', models.CharField(max_length=128)),
                ('kind', models.CharField(max_length=32)),
                ('contract_version', models.PositiveIntegerField(default=1)),
                ('declaration_snapshot', models.JSONField(default=dict)),
                ('schema_metadata', models.JSONField(default=dict)),
                ('observed_state', models.CharField(choices=[('discovered', 'Discovered'), ('available', 'Available'), ('started', 'Started'), ('stopped', 'Stopped'), ('incompatible', 'Incompatible'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('restart-pending', 'Restart pending'), ('uninstalled', 'Uninstalled')], default='discovered', max_length=24)),
                ('health', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failed', 'Failed'), ('incompatible', 'Incompatible'), ('rejected', 'Rejected')], default='unknown', max_length=16)),
                ('diagnostics', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('plugin_id', 'capability_id'),
                'constraints': [models.UniqueConstraint(fields=('plugin_id', 'capability_id'), name='api_plugin_capability_unique'), models.CheckConstraint(condition=models.Q(('contract_version__gte', 1)), name='api_plugin_capability_version_positive')],
            },
        ),
        migrations.CreateModel(
            name='PluginDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_id', models.CharField(max_length=128)),
                ('collection', models.CharField(max_length=128)),
                ('document_id', models.CharField(max_length=128)),
                ('schema_id', models.CharField(max_length=256)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('document', models.JSONField(default=dict)),
                ('update_version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('plugin_id', 'collection', 'document_id'),
                'indexes': [models.Index(fields=['plugin_id', 'collection', 'updated_at'], name='api_plugin_document_query_idx')],
                'constraints': [models.UniqueConstraint(fields=('plugin_id', 'collection', 'document_id'), name='api_plugin_document_unique'), models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='api_plugin_document_schema_positive'), models.CheckConstraint(condition=models.Q(('update_version__gte', 1)), name='api_plugin_document_version_positive')],
            },
        ),
        migrations.CreateModel(
            name='PluginInstallation',
            fields=[
                ('plugin_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('distribution_id', models.CharField(max_length=128)),
                ('installed_version', models.CharField(max_length=64)),
                ('manifest_snapshot', models.JSONField(default=dict)),
                ('provenance_snapshot', models.JSONField(default=dict)),
                ('desired_state', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='disabled', max_length=16)),
                ('observed_state', models.CharField(choices=[('discovered', 'Discovered'), ('available', 'Available'), ('started', 'Started'), ('stopped', 'Stopped'), ('incompatible', 'Incompatible'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('restart-pending', 'Restart pending'), ('uninstalled', 'Uninstalled')], default='discovered', max_length=24)),
                ('aggregate_health', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failed', 'Failed'), ('incompatible', 'Incompatible'), ('rejected', 'Rejected')], default='unknown', max_length=16)),
                ('lifecycle_impact', models.JSONField(default=dict)),
                ('active_generation', models.CharField(blank=True, max_length=128)),
                ('last_known_good_generation', models.CharField(blank=True, max_length=128)),
                ('retained_data', models.BooleanField(default=False)),
                ('update_version', models.PositiveBigIntegerField(default=1)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('plugin_id',),
                'indexes': [models.Index(fields=['desired_state', 'observed_state'], name='api_plugin_install_state_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('plugin_id', ''), _negated=True), name='api_plugin_install_id_nonempty'), models.CheckConstraint(condition=models.Q(('update_version__gte', 1)), name='api_plugin_install_version_positive')],
            },
        ),
        migrations.CreateModel(
            name='PluginInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_id', models.CharField(max_length=128)),
                ('capability_id', models.CharField(max_length=128)),
                ('instance_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=160)),
                ('configuration_version', models.PositiveIntegerField(default=1)),
                ('configuration', models.JSONField(default=dict)),
                ('desired_state', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='disabled', max_length=16)),
                ('observed_state', models.CharField(choices=[('discovered', 'Discovered'), ('available', 'Available'), ('started', 'Started'), ('stopped', 'Stopped'), ('incompatible', 'Incompatible'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('restart-pending', 'Restart pending'), ('uninstalled', 'Uninstalled')], default='stopped', max_length=24)),
                ('runtime_facts', models.JSONField(default=dict)),
                ('update_version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('plugin_id', 'capability_id', 'display_name', 'instance_id'),
                'indexes': [models.Index(fields=['plugin_id', 'capability_id', 'desired_state'], name='api_plugin_instance_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('plugin_id', 'capability_id', 'instance_id'), name='api_plugin_instance_unique'), models.CheckConstraint(condition=models.Q(('configuration_version__gte', 1)), name='api_plugin_instance_schema_positive'), models.CheckConstraint(condition=models.Q(('update_version__gte', 1)), name='api_plugin_instance_version_positive')],
            },
        ),
        migrations.CreateModel(
            name='PluginOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_id', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('install', 'Install'), ('enable', 'Enable'), ('disable', 'Disable'), ('update', 'Update'), ('uninstall', 'Uninstall'), ('retry', 'Retry'), ('cleanup', 'Cleanup'), ('rollback', 'Rollback')], max_length=16)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('running', 'Running'), ('restart-pending', 'Restart pending'), ('verifying', 'Verifying'), ('rolling-back', 'Rolling back'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=24)),
                ('stage', models.CharField(default='requested', max_length=64)),
                ('idempotency_key', models.CharField(max_length=256, unique=True)),
                ('concurrency_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('effective_lifecycle_impact', models.CharField(default='hot', max_length=24)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('diagnostics', models.JSONField(default=list)),
                ('input_generation', models.CharField(blank=True, max_length=128)),
                ('output_generation', models.CharField(blank=True, max_length=128)),
                ('cancellation_requested', models.BooleanField(default=False)),
                ('cancellation_allowed', models.BooleanField(default=True)),
                ('stage_data', models.JSONField(default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plugin_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='PluginDiagnosticRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_id', models.CharField(max_length=128)),
                ('capability_id', models.CharField(blank=True, max_length=128)),
                ('stage', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=2048)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_records', to='api.pluginoperation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PluginSecretReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_id', models.CharField(max_length=128)),
                ('secret_id', models.CharField(max_length=128)),
                ('storage_key', models.CharField(max_length=64, unique=True)),
                ('update_version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('plugin_id', 'secret_id'),
                'constraints': [models.UniqueConstraint(fields=('plugin_id', 'secret_id'), name='api_plugin_secret_unique'), models.CheckConstraint(condition=models.Q(('update_version__gte', 1)), name='api_plugin_secret_version_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='pluginoperation',
            index=models.Index(fields=['status', 'requested_at'], name='api_plugin_operation_state_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginoperation',
            index=models.Index(fields=['plugin_id', 'requested_at'], name='api_plugin_operation_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='pluginoperation',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='api_plugin_operation_progress_range'),
        ),
        migrations.AddIndex(
            model_name='plugindiagnosticrecord',
            index=models.Index(fields=['plugin_id', 'created_at'], name='api_plugin_diag_owner_idx'),
        ),
    ]
