"""Explicit application and audio-processing plugin contracts."""

from .contracts import (
    APPLICATION_PLUGIN_ENTRY_POINT,
    PLUGIN_CONTRACT_VERSION,
    PROCESSING_PLUGIN_ENTRY_POINT,
    ApplicationLifecycleContext,
    ApplicationPlugin,
    ApplicationPluginManifest,
    ConfigurationMigration,
    PluginCompatibility,
    PluginDiagnostic,
    PluginHealth,
    PluginKind,
    PluginLifecycleState,
    ProcessingDriver,
    ProcessingDriverRequest,
    ProcessingDriverResult,
    ProcessingHookContext,
    ProcessingNodeTypeManifest,
    ProcessingPlan,
    ProcessingPlugin,
    ProcessingPluginManifest,
    ProcessingValidationIssue,
)
from .execution import (
    ProcessingDriverExecution,
    ProcessingDriverExecutor,
    ProcessingDriverFailureClassification,
    ProcessingDriverHook,
    ProcessingHookRunner,
    ProcessingPlanningOutcome,
    ProcessingValidationOutcome,
)
from .registry import (
    DuplicatePluginIdError,
    PluginRecord,
    PluginRegistrationError,
    PluginRegistry,
    ProhibitedAudioCapabilityError,
)

__all__ = [
    "APPLICATION_PLUGIN_ENTRY_POINT",
    "PLUGIN_CONTRACT_VERSION",
    "PROCESSING_PLUGIN_ENTRY_POINT",
    "ApplicationLifecycleContext",
    "ApplicationPlugin",
    "ApplicationPluginManifest",
    "ConfigurationMigration",
    "DuplicatePluginIdError",
    "PluginCompatibility",
    "PluginDiagnostic",
    "PluginHealth",
    "PluginKind",
    "PluginLifecycleState",
    "PluginRecord",
    "PluginRegistrationError",
    "PluginRegistry",
    "ProhibitedAudioCapabilityError",
    "ProcessingDriver",
    "ProcessingDriverExecution",
    "ProcessingDriverExecutor",
    "ProcessingDriverFailureClassification",
    "ProcessingDriverHook",
    "ProcessingDriverRequest",
    "ProcessingDriverResult",
    "ProcessingHookContext",
    "ProcessingHookRunner",
    "ProcessingNodeTypeManifest",
    "ProcessingPlan",
    "ProcessingPlanningOutcome",
    "ProcessingPlugin",
    "ProcessingPluginManifest",
    "ProcessingValidationIssue",
    "ProcessingValidationOutcome",
]
