---
- name: Restart Redis
  ansible.builtin.systemd:
    name: redis-server
    state: restarted
    daemon_reload: true

- name: Restart open-cinema
  ansible.builtin.systemd:
    name: open-cinema
    state: restarted
    daemon_reload: true

- name: Restart celery
  ansible.builtin.systemd:
    name: celery
    state: restarted
    daemon_reload: true
  when: open_cinema.celery_enabled | bool

- name: Restart celery beat
  ansible.builtin.systemd:
    name: celery-beat
    state: restarted
    daemon_reload: true
  when: open_cinema.celery_enabled | bool

- name: Restart open-cinema orchestrator
  ansible.builtin.systemd:
    name: open-cinema-orchestrator
    state: restarted
    daemon_reload: true
  when: open_cinema.orchestrator_enabled | bool
