---
- name: Restart open-cinema
  ansible.builtin.systemd:
    name: open-cinema
    state: restarted
    daemon_reload: true

- name: Restart celery
  ansible.builtin.systemd:
    name: celery
    state: restarted
    daemon_reload: true
